# Введение в комбинирование Data with Pandas' `merge`, `join`, and `concat`

Эта записная книжка содержит примеры кода для использования с одноименной статьей, а также краткие комментарии к каждому из примеров.

In [2]:
import pandas as pd

pd.set_option("display.max_columns", 50)

## Importing Data

Здесь вы импортируете наборы данных климатических норм температуры и осадков в DataFrames. Вызов `.head()` в DataFrame даст вам предварительный просмотр 5 строк ваших данных, а атрибут `shape` даст вам размеры данных в форме `(rows, columns)`. Это отличные проверки работоспособности, которые нужно выполнить, прежде чем делать слишком много с данными.

In [3]:
climate_temp = pd.read_csv("climate_temp.csv")
climate_temp.head()

STATION            STATION_NAME ELEVATION  LATITUDE   LONGITUDE  \
0  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
1  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
2  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
3  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
4  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   

       DATE  DLY-CLDD-BASE45  DLY-CLDD-BASE50  DLY-CLDD-BASE55  \
0  20100101                6                2            -7777   
1  20100102                6                2                1   
2  20100103                6                2                1   
3  20100104                6                2                1   
4  20100105                6                2                1   

   DLY-CLDD-BASE57  DLY-CLDD-BASE60  DLY-CLDD-NORMAL  DLY-CLDD-BASE70  \
0            -7777            -7777                0                0   
1            -7777            -7777                0                0   
2            -7777            -7777                0                0   
3            -7777            -7777                0                0   
4            -7777            -7777                0                0   

   DLY-CLDD-BASE72  DLY-HTDD-BASE40  DLY-HTDD-BASE45  DLY-HTDD-BASE50  \
0                0            -7777                1                2   
1                0            -7777                1                2   
2                0            -7777                1                2   
3                0            -7777                1                2   
4                0            -7777            -7777                2   

   DLY-HTDD-BASE55  DLY-HTDD-BASE57  DLY-HTDD-BASE60  DLY-HTDD-NORMAL  
0                6                7               10               15  
1                6                7               10               15  
2                5                7               10               15  
3                5                7               10               15  
4                5                7               10               15

In [4]:
climate_temp.shape

(127020, 21)

In [5]:
climate_precip = pd.read_csv("climate_precip.csv")
climate_precip.head()

STATION            STATION_NAME      DATE  DLY-PRCP-25PCTL  \
0  GHCND:USC00049099  TWENTYNINE PALMS CA US  20100101            -6.66   
1  GHCND:USC00049099  TWENTYNINE PALMS CA US  20100102            -6.66   
2  GHCND:USC00049099  TWENTYNINE PALMS CA US  20100103            -6.66   
3  GHCND:USC00049099  TWENTYNINE PALMS CA US  20100104            -6.66   
4  GHCND:USC00049099  TWENTYNINE PALMS CA US  20100105            -6.66   

   DLY-SNWD-25PCTL  DLY-SNOW-25PCTL  DLY-PRCP-50PCTL  DLY-SNWD-50PCTL  \
0             -666            -66.6            -6.66             -666   
1             -666            -66.6            -6.66             -666   
2             -666            -66.6            -6.66             -666   
3            -9999          -9999.0            -6.66            -9999   
4            -9999          -9999.0            -6.66            -9999   

   DLY-SNOW-50PCTL  DLY-PRCP-75PCTL  DLY-SNWD-75PCTL  DLY-SNOW-75PCTL  \
0            -66.6            -6.66             -666            -66.6   
1            -66.6            -6.66             -666            -66.6   
2            -66.6            -6.66             -666            -66.6   
3          -9999.0            -6.66            -9999          -9999.0   
4          -9999.0            -6.66            -9999          -9999.0   

   MTD-PRCP-NORMAL  MTD-SNOW-NORMAL  YTD-PRCP-NORMAL  YTD-SNOW-NORMAL  \
0             0.02              0.0             0.02              0.0   
1             0.04              0.0             0.04              0.0   
2             0.05              0.0             0.05              0.0   
3             0.07              0.0             0.07              0.0   
4             0.09              0.0             0.09              0.0   

   DLY-PRCP-PCTALL-GE001HI  DLY-PRCP-PCTALL-GE010HI  DLY-PRCP-PCTALL-GE050HI  \
0                       98                       43                       12   
1                       99                       44                       12   
2                      100                       44                       12   
3                      101                       45                       12   
4                      102                       45                       12   

   DLY-PRCP-PCTALL-GE100HI  DLY-SNWD-PCTALL-GE001WI  DLY-SNWD-PCTALL-GE010WI  \
0                        3                    -9999                        0   
1                        3                    -9999                        0   
2                        3                    -9999                        0   
3                        3                        0                        0   
4                        3                        0                        0   

   DLY-SNWD-PCTALL-GE003WI  DLY-SNWD-PCTALL-GE005WI  DLY-SNOW-PCTALL-GE001TI  \
0                    -9999                    -9999                    -9999   
1                    -9999                    -9999                    -9999   
2                    -9999                    -9999                    -9999   
3                        0                        0                        0   
4                        0                        0                        0   

   DLY-SNOW-PCTALL-GE010TI  DLY-SNOW-PCTALL-GE100TI  DLY-SNOW-PCTALL-GE030TI  \
0                    -9999                        0                    -9999   
1                    -9999                        0                    -9999   
2                    -9999                        0                    -9999   
3                        0                        0                        0   
4                        0                        0                        0   

   DLY-SNOW-PCTALL-GE050TI  
0                    -9999  
1                    -9999  
2                    -9999  
3                        0  
4                        0

In [6]:
climate_precip.shape

(151110, 29)

## merge()

В этом разделе вы узнаете о функциональности merge() в Pandas.

### Inner Join

Здесь вы будете использовать простой вызов `merge()` для выполнения внутреннего соединения и узнаете, как это может привести к меньшему, более целенаправленному набору данных. Сначала вы создадите новый объект DataFrame, содержащий данные об осадках с одной станции.

In [7]:
precip_one_station = climate_precip[climate_precip["STATION"] == 'GHCND:USC00045721']

In [9]:
precip_one_station.shape

(365, 29)

In [10]:
precip_one_station

STATION            STATION_NAME      DATE  DLY-PRCP-25PCTL  \
1460  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100101             0.04   
1461  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100102             0.05   
1462  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100103             0.05   
1463  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100104             0.05   
1464  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100105             0.05   
...                 ...                     ...       ...              ...   
1820  GHCND:USC00045721  MITCHELL CAVERNS CA US  20101227             0.04   
1821  GHCND:USC00045721  MITCHELL CAVERNS CA US  20101228             0.04   
1822  GHCND:USC00045721  MITCHELL CAVERNS CA US  20101229             0.04   
1823  GHCND:USC00045721  MITCHELL CAVERNS CA US  20101230             0.04   
1824  GHCND:USC00045721  MITCHELL CAVERNS CA US  20101231             0.04   

      DLY-SNWD-25PCTL  DLY-SNOW-25PCTL  DLY-PRCP-50PCTL  DLY-SNWD-50PCTL  \
1460             -666            -66.6             0.16             -666   
1461             -666            -66.6             0.16             -666   
1462             -666            -66.6             0.16             -666   
1463             -666            -66.6             0.16             -666   
1464             -666            -66.6             0.17             -666   
...               ...              ...              ...              ...   
1820             -666            -66.6             0.15             -666   
1821             -666            -66.6             0.15             -666   
1822             -666            -66.6             0.15             -666   
1823             -666            -66.6             0.15             -666   
1824             -666            -66.6             0.15             -666   

      DLY-SNOW-50PCTL  DLY-PRCP-75PCTL  DLY-SNWD-75PCTL  DLY-SNOW-75PCTL  \
1460            -66.6             0.44             -666            -66.6   
1461            -66.6             0.44             -666            -66.6   
1462            -66.6             0.45             -666            -66.6   
1463            -66.6             0.45             -666            -66.6   
1464            -66.6             0.46             -666            -66.6   
...               ...              ...              ...              ...   
1820            -66.6             0.44             -666            -66.6   
1821            -66.6             0.43             -666            -66.6   
1822            -66.6             0.43             -666            -66.6   
1823            -66.6             0.43             -666            -66.6   
1824            -66.6             0.44             -666            -66.6   

      MTD-PRCP-NORMAL  MTD-SNOW-NORMAL  YTD-PRCP-NORMAL  YTD-SNOW-NORMAL  \
1460             0.04              0.0             0.04              0.0   
1461             0.08              0.0             0.08              0.0   
1462             0.12              0.0             0.12              0.0   
1463             0.16              0.0             0.16              0.0   
1464             0.21              0.0             0.21              0.0   
...               ...              ...              ...              ...   
1820             1.14              0.3            11.29              1.5   
1821             1.19              0.3            11.34              1.5   
1822             1.24              0.3            11.39              1.5   
1823             1.30              0.3            11.45              1.5   
1824             1.35              0.3            11.50              1.5   

      DLY-PRCP-PCTALL-GE001HI  DLY-PRCP-PCTALL-GE010HI  \
1460                      137                       81   
1461                      138                       83   
1462                      139                       84   
1463                      140                       85   
1464                      141                     

In [11]:
precip_one_station = climate_precip.query("STATION == 'GHCND:USC00045721'")
precip_one_station.head()

STATION            STATION_NAME      DATE  DLY-PRCP-25PCTL  \
1460  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100101             0.04   
1461  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100102             0.05   
1462  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100103             0.05   
1463  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100104             0.05   
1464  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100105             0.05   

      DLY-SNWD-25PCTL  DLY-SNOW-25PCTL  DLY-PRCP-50PCTL  DLY-SNWD-50PCTL  \
1460             -666            -66.6             0.16             -666   
1461             -666            -66.6             0.16             -666   
1462             -666            -66.6             0.16             -666   
1463             -666            -66.6             0.16             -666   
1464             -666            -66.6             0.17             -666   

      DLY-SNOW-50PCTL  DLY-PRCP-75PCTL  DLY-SNWD-75PCTL  DLY-SNOW-75PCTL  \
1460            -66.6             0.44             -666            -66.6   
1461            -66.6             0.44             -666            -66.6   
1462            -66.6             0.45             -666            -66.6   
1463            -66.6             0.45             -666            -66.6   
1464            -66.6             0.46             -666            -66.6   

      MTD-PRCP-NORMAL  MTD-SNOW-NORMAL  YTD-PRCP-NORMAL  YTD-SNOW-NORMAL  \
1460             0.04              0.0             0.04              0.0   
1461             0.08              0.0             0.08              0.0   
1462             0.12              0.0             0.12              0.0   
1463             0.16              0.0             0.16              0.0   
1464             0.21              0.0             0.21              0.0   

      DLY-PRCP-PCTALL-GE001HI  DLY-PRCP-PCTALL-GE010HI  \
1460                      137                       81   
1461                      138                       83   
1462                      139                       84   
1463                      140                       85   
1464                      141                       86   

      DLY-PRCP-PCTALL-GE050HI  DLY-PRCP-PCTALL-GE100HI  \
1460                       31                       11   
1461                       31                       11   
1462                       31                       11   
1463                       32                       11   
1464                       32                       11   

      DLY-SNWD-PCTALL-GE001WI  DLY-SNWD-PCTALL-GE010WI  \
1460                        4                        0   
1461                        4                        0   
1462                        4                        0   
1463                        4                        0   
1464                        4                        0   

      DLY-SNWD-PCTALL-GE003WI  DLY-SNWD-PCTALL-GE005WI  \
1460                        3                        3   
1461                        3                        3   
1462                        3                        3   
1463                        3                        2   
1464                        3                        2   

      DLY-SNOW-PCTALL-GE001TI  DLY-SNOW-PCTALL-GE010TI  \
1460                        9                        6   
1461                       10                        6   
1462                       10                        6   
1463                       10                        6   
1464                       10                        6   

      DLY-SNOW-PCTALL-GE100TI  DLY-SNOW-PCTALL-GE030TI  \
1460                        0                    -9999   
1461                        0                    -9999   
1462                        0                    -9999   
1463                        0                    -9999   
1464                        0                    -9999   

      DLY-SNOW-PCTALL-GE050TI  
1460                    -9999  
1461              

In [12]:
precip_one_station.shape

(365, 29)

In [ ]:
#29 21 из 3 общие. 

In [16]:
29+21 - 3

47

In [17]:
climate_temp.shape

(127020, 21)

In [37]:
precip_one_station.iloc[1]['DATE']=20100103

In [39]:
precip_one_station

STATION            STATION_NAME      DATE  DLY-PRCP-25PCTL  \
1460  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100101             0.04   
1461  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100102             0.05   
1462  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100103             0.05   
1463  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100104             0.05   
1464  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100105             0.05   
...                 ...                     ...       ...              ...   
1820  GHCND:USC00045721  MITCHELL CAVERNS CA US  20101227             0.04   
1821  GHCND:USC00045721  MITCHELL CAVERNS CA US  20101228             0.04   
1822  GHCND:USC00045721  MITCHELL CAVERNS CA US  20101229             0.04   
1823  GHCND:USC00045721  MITCHELL CAVERNS CA US  20101230             0.04   
1824  GHCND:USC00045721  MITCHELL CAVERNS CA US  20101231             0.04   

      DLY-SNWD-25PCTL  DLY-SNOW-25PCTL  DLY-PRCP-50PCTL  DLY-SNWD-50PCTL  \
1460             -666            -66.6             0.16             -666   
1461             -666            -66.6             0.16             -666   
1462             -666            -66.6             0.16             -666   
1463             -666            -66.6             0.16             -666   
1464             -666            -66.6             0.17             -666   
...               ...              ...              ...              ...   
1820             -666            -66.6             0.15             -666   
1821             -666            -66.6             0.15             -666   
1822             -666            -66.6             0.15             -666   
1823             -666            -66.6             0.15             -666   
1824             -666            -66.6             0.15             -666   

      DLY-SNOW-50PCTL  DLY-PRCP-75PCTL  DLY-SNWD-75PCTL  DLY-SNOW-75PCTL  \
1460            -66.6             0.44             -666            -66.6   
1461            -66.6             0.44             -666            -66.6   
1462            -66.6             0.45             -666            -66.6   
1463            -66.6             0.45             -666            -66.6   
1464            -66.6             0.46             -666            -66.6   
...               ...              ...              ...              ...   
1820            -66.6             0.44             -666            -66.6   
1821            -66.6             0.43             -666            -66.6   
1822            -66.6             0.43             -666            -66.6   
1823            -66.6             0.43             -666            -66.6   
1824            -66.6             0.44             -666            -66.6   

      MTD-PRCP-NORMAL  MTD-SNOW-NORMAL  YTD-PRCP-NORMAL  YTD-SNOW-NORMAL  \
1460             0.04              0.0             0.04              0.0   
1461             0.08              0.0             0.08              0.0   
1462             0.12              0.0             0.12              0.0   
1463             0.16              0.0             0.16              0.0   
1464             0.21              0.0             0.21              0.0   
...               ...              ...              ...              ...   
1820             1.14              0.3            11.29              1.5   
1821             1.19              0.3            11.34              1.5   
1822             1.24              0.3            11.39              1.5   
1823             1.30              0.3            11.45              1.5   
1824             1.35              0.3            11.50              1.5   

      DLY-PRCP-PCTALL-GE001HI  DLY-PRCP-PCTALL-GE010HI  \
1460                      137                       81   
1461                      138                       83   
1462                      139                       84   
1463                      140                       85   
1464                      141                     

In [40]:
inner_merged = pd.merge(precip_one_station, climate_temp)
inner_merged.head()

STATION            STATION_NAME      DATE  DLY-PRCP-25PCTL  \
0  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100101             0.04   
1  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100102             0.05   
2  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100103             0.05   
3  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100104             0.05   
4  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100105             0.05   

   DLY-SNWD-25PCTL  DLY-SNOW-25PCTL  DLY-PRCP-50PCTL  DLY-SNWD-50PCTL  \
0             -666            -66.6             0.16             -666   
1             -666            -66.6             0.16             -666   
2             -666            -66.6             0.16             -666   
3             -666            -66.6             0.16             -666   
4             -666            -66.6             0.17             -666   

   DLY-SNOW-50PCTL  DLY-PRCP-75PCTL  DLY-SNWD-75PCTL  DLY-SNOW-75PCTL  \
0            -66.6             0.44             -666            -66.6   
1            -66.6             0.44             -666            -66.6   
2            -66.6             0.45             -666            -66.6   
3            -66.6             0.45             -666            -66.6   
4            -66.6             0.46             -666            -66.6   

   MTD-PRCP-NORMAL  MTD-SNOW-NORMAL  YTD-PRCP-NORMAL  YTD-SNOW-NORMAL  \
0             0.04              0.0             0.04              0.0   
1             0.08              0.0             0.08              0.0   
2             0.12              0.0             0.12              0.0   
3             0.16              0.0             0.16              0.0   
4             0.21              0.0             0.21              0.0   

   DLY-PRCP-PCTALL-GE001HI  DLY-PRCP-PCTALL-GE010HI  DLY-PRCP-PCTALL-GE050HI  \
0                      137                       81                       31   
1                      138                       83                       31   
2                      139                       84                       31   
3                      140                       85                       32   
4                      141                       86                       32   

   DLY-PRCP-PCTALL-GE100HI  DLY-SNWD-PCTALL-GE001WI  DLY-SNWD-PCTALL-GE010WI  \
0                       11                        4                        0   
1                       11                        4                        0   
2                       11                        4                        0   
3                       11                        4                        0   
4                       11                        4                        0   

   DLY-SNWD-PCTALL-GE003WI  DLY-SNWD-PCTALL-GE005WI  DLY-SNOW-PCTALL-GE001TI  \
0                        3                        3                        9   
1                        3                        3                       10   
2                        3                        3                       10   
3                        3                        2                       10   
4                        3                        2                       10   

   DLY-SNOW-PCTALL-GE010TI  DLY-SNOW-PCTALL-GE100TI  DLY-SNOW-PCTALL-GE030TI  \
0                        6                        0                    -9999   
1                        6                        0                    -9999   
2                        6                        0                    -9999   
3                        6                        0                    -9999   
4                        6                        0                    -9999   

   DLY-SNOW-PCTALL-GE050TI ELEVATION LATITUDE  LONGITUDE  DLY-CLDD-BASE45  \
0                    -9999    1325.9  34.9436  -115.5469                3   
1                    -9999    1325.9  34.9436  -115.5469                3   
2                    -9999    1325.9  34.9436  -115.5469                3   
3            

Как вы думаете, сколько строк имеет этот объединенный DataFrame?

In [41]:
inner_merged.shape

(365, 47)

In [42]:
inner_merged

STATION            STATION_NAME      DATE  DLY-PRCP-25PCTL  \
0    GHCND:USC00045721  MITCHELL CAVERNS CA US  20100101             0.04   
1    GHCND:USC00045721  MITCHELL CAVERNS CA US  20100102             0.05   
2    GHCND:USC00045721  MITCHELL CAVERNS CA US  20100103             0.05   
3    GHCND:USC00045721  MITCHELL CAVERNS CA US  20100104             0.05   
4    GHCND:USC00045721  MITCHELL CAVERNS CA US  20100105             0.05   
..                 ...                     ...       ...              ...   
360  GHCND:USC00045721  MITCHELL CAVERNS CA US  20101227             0.04   
361  GHCND:USC00045721  MITCHELL CAVERNS CA US  20101228             0.04   
362  GHCND:USC00045721  MITCHELL CAVERNS CA US  20101229             0.04   
363  GHCND:USC00045721  MITCHELL CAVERNS CA US  20101230             0.04   
364  GHCND:USC00045721  MITCHELL CAVERNS CA US  20101231             0.04   

     DLY-SNWD-25PCTL  DLY-SNOW-25PCTL  DLY-PRCP-50PCTL  DLY-SNWD-50PCTL  \
0               -666            -66.6             0.16             -666   
1               -666            -66.6             0.16             -666   
2               -666            -66.6             0.16             -666   
3               -666            -66.6             0.16             -666   
4               -666            -66.6             0.17             -666   
..               ...              ...              ...              ...   
360             -666            -66.6             0.15             -666   
361             -666            -66.6             0.15             -666   
362             -666            -66.6             0.15             -666   
363             -666            -66.6             0.15             -666   
364             -666            -66.6             0.15             -666   

     DLY-SNOW-50PCTL  DLY-PRCP-75PCTL  DLY-SNWD-75PCTL  DLY-SNOW-75PCTL  \
0              -66.6             0.44             -666            -66.6   
1              -66.6             0.44             -666            -66.6   
2              -66.6             0.45             -666            -66.6   
3              -66.6             0.45             -666            -66.6   
4              -66.6             0.46             -666            -66.6   
..               ...              ...              ...              ...   
360            -66.6             0.44             -666            -66.6   
361            -66.6             0.43             -666            -66.6   
362            -66.6             0.43             -666            -66.6   
363            -66.6             0.43             -666            -66.6   
364            -66.6             0.44             -666            -66.6   

     MTD-PRCP-NORMAL  MTD-SNOW-NORMAL  YTD-PRCP-NORMAL  YTD-SNOW-NORMAL  \
0               0.04              0.0             0.04              0.0   
1               0.08              0.0             0.08              0.0   
2               0.12              0.0             0.12              0.0   
3               0.16              0.0             0.16              0.0   
4               0.21              0.0             0.21              0.0   
..               ...              ...              ...              ...   
360             1.14              0.3            11.29              1.5   
361             1.19              0.3            11.34              1.5   
362             1.24              0.3            11.39              1.5   
363             1.30              0.3            11.45              1.5   
364             1.35              0.3            11.50              1.5   

     DLY-PRCP-PCTALL-GE001HI  DLY-PRCP-PCTALL-GE010HI  \
0                        137                       81   
1                        138                       83   
2                        139                       84   
3                        140                       85   
4                        141                       86   
..                       ...                 

Вы получаете 365 строк, потому что любые несоответствующие строки отбрасываются во внутреннем соединении, которое является методом слияния по умолчанию для вызова `merge()`, а `precip_one_station` имеет только 365 строк.

Что, если вы хотите объединить оба полных набора данных, но указать, какие столбцы объединять? В этом случае вы будете использовать параметр on:

In [44]:
climate_temp.columns

Index(['STATION', 'STATION_NAME', 'ELEVATION', 'LATITUDE', 'LONGITUDE', 'DATE',
       'DLY-CLDD-BASE45', 'DLY-CLDD-BASE50', 'DLY-CLDD-BASE55',
       'DLY-CLDD-BASE57', 'DLY-CLDD-BASE60', 'DLY-CLDD-NORMAL',
       'DLY-CLDD-BASE70', 'DLY-CLDD-BASE72', 'DLY-HTDD-BASE40',
       'DLY-HTDD-BASE45', 'DLY-HTDD-BASE50', 'DLY-HTDD-BASE55',
       'DLY-HTDD-BASE57', 'DLY-HTDD-BASE60', 'DLY-HTDD-NORMAL'],
      dtype='object')

In [45]:
for i in climate_temp.columns:
 if i in climate_precip.columns:
    print(i)

STATION
STATION_NAME
DATE


In [46]:
print(climate_temp.shape)
print(climate_precip.shape)

(127020, 21)
(151110, 29)


In [55]:
inner_merged_total = pd.merge(
    climate_temp, climate_precip, on=["STATION", "DATE"]
)
inner_merged_total.head(20)

STATION          STATION_NAME_x ELEVATION  LATITUDE   LONGITUDE  \
0   GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
1   GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
2   GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
3   GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
4   GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
5   GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
6   GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
7   GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
8   GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
9   GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
10  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
11  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
12  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
13  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
14  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
15  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
16  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
17  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
18  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
19  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   

        DATE  DLY-CLDD-BASE45  DLY-CLDD-BASE50  DLY-CLDD-BASE55  \
0   20100101                6                2            -7777   
1   20100102                6                2                1   
2   20100103                6                2                1   
3   20100104                6                2                1   
4   20100105                6                2                1   
5   20100106                6                2                1   
6   20100107                6                2                1   
7   20100108                6                3                1   
8   20100109                6                3                1   
9   20100110                6                3                1   
10  20100111                6                3                1   
11  20100112                6                3                1   
12  20100113                6                3                1   
13  20100114                6                3                1   
14  20100115                6                3                1   
15  20100116                7                3                1   
16  20100117                7                3                1   
17  20100118                7                3                1   
18  20100119                7                3                1   
19  20100120                7                3                1   

    DLY-CLDD-BASE57  DLY-CLDD-BASE60  DLY-CLDD-NORMAL  DLY-CLDD-BASE70  \
0             -7777            -7777                0                0   
1             -7777            -7777                0                0   
2             -7777            -7777                0                0   
3             -7777            -7777                0                0   
4             -7777            -7777                0                0   
5             -7777            -7777                0                0   
6             -7777            -7777                0                0   
7             -7777            -7777                0                0   
8             -7777            -7777                0                0   
9             -7777            -7777                0                0   
10            -7777            -7777            -7777                0   
11            -7

In [56]:
inner_merged_total.shape

(123005, 48)

Вы можете указать один _ключевой столбец_ со строкой или несколько ключевых столбцов со списком, как в приведенном выше примере. В результате получается DataFrame с 123005 строками и 48 столбцами.

Почему 48 столбцов вместо 47? Поскольку вы указали столбцы ключей для объединения, Pandas не пытается объединить все объединяемые столбцы. Это может привести к «дублированию» имен столбцов, которые могут иметь или не иметь разные значения. «Дублировать» заключено в кавычки, потому что столбцы на самом деле будут иметь новые имена, по умолчанию к ним добавляются `_x` и `_y`. Вы также можете использовать параметр `suffixes`, чтобы управлять тем, что добавляется к именам столбцов.

### Outer Join
При внешнем объединении вы также сохраните строки, в которых нет совпадений. В этом примере вы будете использовать меньший фрейм данных об осадках «precip_one_station» с полным фреймом данных «climate_temp» и соединить столбцы «STATION» и «DATE» в качестве ключевых столбцов. Потратьте секунду и подумайте, сколько строк вы ожидаете от нового DataFrame.

In [57]:
outer_merged = pd.merge(
    precip_one_station, climate_temp, how="outer", on=["STATION", "DATE"]
)
outer_merged.head()

STATION          STATION_NAME_x      DATE  DLY-PRCP-25PCTL  \
0  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100101             0.04   
1  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100102             0.05   
2  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100103             0.05   
3  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100104             0.05   
4  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100105             0.05   

   DLY-SNWD-25PCTL  DLY-SNOW-25PCTL  DLY-PRCP-50PCTL  DLY-SNWD-50PCTL  \
0           -666.0            -66.6             0.16           -666.0   
1           -666.0            -66.6             0.16           -666.0   
2           -666.0            -66.6             0.16           -666.0   
3           -666.0            -66.6             0.16           -666.0   
4           -666.0            -66.6             0.17           -666.0   

   DLY-SNOW-50PCTL  DLY-PRCP-75PCTL  DLY-SNWD-75PCTL  DLY-SNOW-75PCTL  \
0            -66.6             0.44           -666.0            -66.6   
1            -66.6             0.44           -666.0            -66.6   
2            -66.6             0.45           -666.0            -66.6   
3            -66.6             0.45           -666.0            -66.6   
4            -66.6             0.46           -666.0            -66.6   

   MTD-PRCP-NORMAL  MTD-SNOW-NORMAL  YTD-PRCP-NORMAL  YTD-SNOW-NORMAL  \
0             0.04              0.0             0.04              0.0   
1             0.08              0.0             0.08              0.0   
2             0.12              0.0             0.12              0.0   
3             0.16              0.0             0.16              0.0   
4             0.21              0.0             0.21              0.0   

   DLY-PRCP-PCTALL-GE001HI  DLY-PRCP-PCTALL-GE010HI  DLY-PRCP-PCTALL-GE050HI  \
0                    137.0                     81.0                     31.0   
1                    138.0                     83.0                     31.0   
2                    139.0                     84.0                     31.0   
3                    140.0                     85.0                     32.0   
4                    141.0                     86.0                     32.0   

   DLY-PRCP-PCTALL-GE100HI  DLY-SNWD-PCTALL-GE001WI  DLY-SNWD-PCTALL-GE010WI  \
0                     11.0                      4.0                      0.0   
1                     11.0                      4.0                      0.0   
2                     11.0                      4.0                      0.0   
3                     11.0                      4.0                      0.0   
4                     11.0                      4.0                      0.0   

   DLY-SNWD-PCTALL-GE003WI  DLY-SNWD-PCTALL-GE005WI  DLY-SNOW-PCTALL-GE001TI  \
0                      3.0                      3.0                      9.0   
1                      3.0                      3.0                     10.0   
2                      3.0                      3.0                     10.0   
3                      3.0                      2.0                     10.0   
4                      3.0                      2.0                     10.0   

   DLY-SNOW-PCTALL-GE010TI  DLY-SNOW-PCTALL-GE100TI  DLY-SNOW-PCTALL-GE030TI  \
0                      6.0                      0.0                  -9999.0   
1                      6.0                      0.0                  -9999.0   
2                      6.0                      0.0                  -9999.0   
3                      6.0                      0.0                  -9999.0   
4                      6.0                      0.0                  -9999.0   

   DLY-SNOW-PCTALL-GE050TI          STATION_NAME_y ELEVATION LATITUDE  \
0                  -9999.0  MITCHELL CAVERNS CA US    1325.9  34.9436   
1                  -9999.0  MITCHELL CAVERNS CA US    1325.9  34.9436   
2                  -9999.0  MITCHELL CAVERNS CA US    1325.9  34.9436   
3                  -9999.0  M

In [58]:
outer_merged.shape

(127020, 48)

In [59]:
outer_merged[1250:1260]

STATION STATION_NAME_x      DATE  DLY-PRCP-25PCTL  \
1250  GHCND:USC00047902            NaN  20100605              NaN   
1251  GHCND:USC00047902            NaN  20100606              NaN   
1252  GHCND:USC00047902            NaN  20100607              NaN   
1253  GHCND:USC00047902            NaN  20100608              NaN   
1254  GHCND:USC00047902            NaN  20100609              NaN   
1255  GHCND:USC00047902            NaN  20100610              NaN   
1256  GHCND:USC00047902            NaN  20100611              NaN   
1257  GHCND:USC00047902            NaN  20100612              NaN   
1258  GHCND:USC00047902            NaN  20100613              NaN   
1259  GHCND:USC00047902            NaN  20100614              NaN   

      DLY-SNWD-25PCTL  DLY-SNOW-25PCTL  DLY-PRCP-50PCTL  DLY-SNWD-50PCTL  \
1250              NaN              NaN              NaN              NaN   
1251              NaN              NaN              NaN              NaN   
1252              NaN              NaN              NaN              NaN   
1253              NaN              NaN              NaN              NaN   
1254              NaN              NaN              NaN              NaN   
1255              NaN              NaN              NaN              NaN   
1256              NaN              NaN              NaN              NaN   
1257              NaN              NaN              NaN              NaN   
1258              NaN              NaN              NaN              NaN   
1259              NaN              NaN              NaN              NaN   

      DLY-SNOW-50PCTL  DLY-PRCP-75PCTL  DLY-SNWD-75PCTL  DLY-SNOW-75PCTL  \
1250              NaN              NaN              NaN              NaN   
1251              NaN              NaN              NaN              NaN   
1252              NaN              NaN              NaN              NaN   
1253              NaN              NaN              NaN              NaN   
1254              NaN              NaN              NaN              NaN   
1255              NaN              NaN              NaN              NaN   
1256              NaN              NaN              NaN              NaN   
1257              NaN              NaN              NaN              NaN   
1258              NaN              NaN              NaN              NaN   
1259              NaN              NaN              NaN              NaN   

      MTD-PRCP-NORMAL  MTD-SNOW-NORMAL  YTD-PRCP-NORMAL  YTD-SNOW-NORMAL  \
1250              NaN              NaN              NaN              NaN   
1251              NaN              NaN              NaN              NaN   
1252              NaN              NaN              NaN              NaN   
1253              NaN              NaN              NaN              NaN   
1254              NaN              NaN              NaN              NaN   
1255              NaN              NaN              NaN              NaN   
1256              NaN              NaN              NaN              NaN   
1257              NaN              NaN              NaN              NaN   
1258              NaN              NaN              NaN              NaN   
1259              NaN              NaN              NaN              NaN   

      DLY-PRCP-PCTALL-GE001HI  DLY-PRCP-PCTALL-GE010HI  \
1250                      NaN                      NaN   
1251                      NaN                      NaN   
1252                      NaN                      NaN   
1253                      NaN                      NaN   
1254                      NaN                      NaN   
1255                      NaN                      NaN   
1256                      NaN                      NaN   
1257                      NaN                      NaN   
1258                      NaN                      NaN   
1259                      NaN                      NaN   

      DLY-PRCP-PCTALL-GE050HI  DLY-PRCP-PCTALL-GE100HI  \
1250                      NaN                   

Если вы помните, когда вы проверяли атрибут `.shape` в `climate_temp`, вы увидите, что количество строк в `outer_merged` совпадает с этим. При внешнем объединении вы можете ожидать, что у вас будет такое же количество строк, как и у большего DataFrame, поскольку ни одна из них не будет потеряна, как при внутреннем соединении

### Left Join
Также известен как левое внешнее соединение. В этом объединении вы сохраните строки, у которых нет совпадений, только в левом (или первом) кадре данных для объединения.

In [60]:
left_merged = pd.merge(
    climate_temp, precip_one_station, how="left", on=["STATION", "DATE"]
)
left_merged.loc[4567:4578]

STATION                 STATION_NAME_x ELEVATION LATITUDE  \
4567  GHCND:USC00042467  DONNER MEMORIAL ST PARK CA US    1809.6  39.3239   
4568  GHCND:USC00042467  DONNER MEMORIAL ST PARK CA US    1809.6  39.3239   
4569  GHCND:USC00042467  DONNER MEMORIAL ST PARK CA US    1809.6  39.3239   
4570  GHCND:USC00042467  DONNER MEMORIAL ST PARK CA US    1809.6  39.3239   
4571  GHCND:USC00042467  DONNER MEMORIAL ST PARK CA US    1809.6  39.3239   
4572  GHCND:USC00042467  DONNER MEMORIAL ST PARK CA US    1809.6  39.3239   
4573  GHCND:USC00042467  DONNER MEMORIAL ST PARK CA US    1809.6  39.3239   
4574  GHCND:USC00042467  DONNER MEMORIAL ST PARK CA US    1809.6  39.3239   
4575  GHCND:USC00042467  DONNER MEMORIAL ST PARK CA US    1809.6  39.3239   
4576  GHCND:USC00042467  DONNER MEMORIAL ST PARK CA US    1809.6  39.3239   
4577  GHCND:USC00042467  DONNER MEMORIAL ST PARK CA US    1809.6  39.3239   
4578  GHCND:USC00042467  DONNER MEMORIAL ST PARK CA US    1809.6  39.3239   

      LONGITUDE      DATE  DLY-CLDD-BASE45  DLY-CLDD-BASE50  DLY-CLDD-BASE55  \
4567  -120.2331  20100707               16               11                7   
4568  -120.2331  20100708               16               11                7   
4569  -120.2331  20100709               17               12                7   
4570  -120.2331  20100710               17               12                7   
4571  -120.2331  20100711               17               12                7   
4572  -120.2331  20100712               17               12                7   
4573  -120.2331  20100713               17               12                8   
4574  -120.2331  20100714               17               13                8   
4575  -120.2331  20100715               18               13                8   
4576  -120.2331  20100716               18               13                8   
4577  -120.2331  20100717               18               13                8   
4578  -120.2331  20100718               18               13                8   

      DLY-CLDD-BASE57  DLY-CLDD-BASE60  DLY-CLDD-NORMAL  DLY-CLDD-BASE70  \
4567                5                3                1            -7777   
4568                5                3                1            -7777   
4569                5                3                1            -7777   
4570                5                3                1            -7777   
4571                6                3                1            -7777   
4572                6                3                1            -7777   
4573                6                3                1            -7777   
4574                6                4                1            -7777   
4575                6                4                1            -7777   
4576                6                4                1            -7777   
4577                6                4                1            -7777   
4578                6                4                1            -7777   

      DLY-CLDD-BASE72  DLY-HTDD-BASE40  DLY-HTDD-BASE45  DLY-HTDD-BASE50  \
4567            -7777                0            -7777            -7777   
4568            -7777                0            -7777            -7777   
4569            -7777                0                0            -7777   
4570            -7777                0                0            -7777   
4571            -7777                0            -7777            -7777   
4572            -7777                0            -7777            -7777   
4573            -7777                0            -7777            -7777   
4574            -7777                0            -7777            -7777   
4575            -7777                0            -7777            -7777   
4576            -7777                0            -7777            -7777   
4577            -7777                0            -7777            -7777   
4578            -7777                0            -7777            -7777

In [22]:
left_merged.shape

(127020, 48)

Здесь вы видите, что количество строк в результирующем кадре данных совпадает с количеством строк в кадре данных «climate_temp». Что, если мы поменяем местами два фрейма данных, которые мы объединяем?

In [61]:
left_merged_reversed = pd.merge(
    precip_one_station, climate_temp, how="left", on=["STATION", "DATE"]
)
left_merged_reversed.head()

STATION          STATION_NAME_x      DATE  DLY-PRCP-25PCTL  \
0  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100101             0.04   
1  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100102             0.05   
2  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100103             0.05   
3  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100104             0.05   
4  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100105             0.05   

   DLY-SNWD-25PCTL  DLY-SNOW-25PCTL  DLY-PRCP-50PCTL  DLY-SNWD-50PCTL  \
0             -666            -66.6             0.16             -666   
1             -666            -66.6             0.16             -666   
2             -666            -66.6             0.16             -666   
3             -666            -66.6             0.16             -666   
4             -666            -66.6             0.17             -666   

   DLY-SNOW-50PCTL  DLY-PRCP-75PCTL  DLY-SNWD-75PCTL  DLY-SNOW-75PCTL  \
0            -66.6             0.44             -666            -66.6   
1            -66.6             0.44             -666            -66.6   
2            -66.6             0.45             -666            -66.6   
3            -66.6             0.45             -666            -66.6   
4            -66.6             0.46             -666            -66.6   

   MTD-PRCP-NORMAL  MTD-SNOW-NORMAL  YTD-PRCP-NORMAL  YTD-SNOW-NORMAL  \
0             0.04              0.0             0.04              0.0   
1             0.08              0.0             0.08              0.0   
2             0.12              0.0             0.12              0.0   
3             0.16              0.0             0.16              0.0   
4             0.21              0.0             0.21              0.0   

   DLY-PRCP-PCTALL-GE001HI  DLY-PRCP-PCTALL-GE010HI  DLY-PRCP-PCTALL-GE050HI  \
0                      137                       81                       31   
1                      138                       83                       31   
2                      139                       84                       31   
3                      140                       85                       32   
4                      141                       86                       32   

   DLY-PRCP-PCTALL-GE100HI  DLY-SNWD-PCTALL-GE001WI  DLY-SNWD-PCTALL-GE010WI  \
0                       11                        4                        0   
1                       11                        4                        0   
2                       11                        4                        0   
3                       11                        4                        0   
4                       11                        4                        0   

   DLY-SNWD-PCTALL-GE003WI  DLY-SNWD-PCTALL-GE005WI  DLY-SNOW-PCTALL-GE001TI  \
0                        3                        3                        9   
1                        3                        3                       10   
2                        3                        3                       10   
3                        3                        2                       10   
4                        3                        2                       10   

   DLY-SNOW-PCTALL-GE010TI  DLY-SNOW-PCTALL-GE100TI  DLY-SNOW-PCTALL-GE030TI  \
0                        6                        0                    -9999   
1                        6                        0                    -9999   
2                        6                        0                    -9999   
3                        6                        0                    -9999   
4                        6                        0                    -9999   

   DLY-SNOW-PCTALL-GE050TI          STATION_NAME_y ELEVATION LATITUDE  \
0                    -9999  MITCHELL CAVERNS CA US    1325.9  34.9436   
1                    -9999  MITCHELL CAVERNS CA US    1325.9  34.9436   
2                    -9999  MITCHELL CAVERNS CA US    1325.9  34.9436   
3                    -9999  M

In [62]:
left_merged_reversed.shape

(365, 48)

### Right Join
This works the same as the left join, however non-matching rows are only retained in the _right_ DataFrame. In the next example, you will recreate the `left_merged` DataFrame but with a right join.

In [40]:
right_merged = pd.merge(
    precip_one_station, climate_temp, how="right", on=["STATION", "DATE"]
)
right_merged.head()

STATION STATION_NAME_x      DATE  DLY-PRCP-25PCTL  \
0  GHCND:USC00049099            NaN  20100101              NaN   
1  GHCND:USC00049099            NaN  20100102              NaN   
2  GHCND:USC00049099            NaN  20100103              NaN   
3  GHCND:USC00049099            NaN  20100104              NaN   
4  GHCND:USC00049099            NaN  20100105              NaN   

   DLY-SNWD-25PCTL  DLY-SNOW-25PCTL  DLY-PRCP-50PCTL  DLY-SNWD-50PCTL  \
0              NaN              NaN              NaN              NaN   
1              NaN              NaN              NaN              NaN   
2              NaN              NaN              NaN              NaN   
3              NaN              NaN              NaN              NaN   
4              NaN              NaN              NaN              NaN   

   DLY-SNOW-50PCTL  DLY-PRCP-75PCTL  DLY-SNWD-75PCTL  DLY-SNOW-75PCTL  \
0              NaN              NaN              NaN              NaN   
1              NaN              NaN              NaN              NaN   
2              NaN              NaN              NaN              NaN   
3              NaN              NaN              NaN              NaN   
4              NaN              NaN              NaN              NaN   

   MTD-PRCP-NORMAL  MTD-SNOW-NORMAL  YTD-PRCP-NORMAL  YTD-SNOW-NORMAL  \
0              NaN              NaN              NaN              NaN   
1              NaN              NaN              NaN              NaN   
2              NaN              NaN              NaN              NaN   
3              NaN              NaN              NaN              NaN   
4              NaN              NaN              NaN              NaN   

   DLY-PRCP-PCTALL-GE001HI  DLY-PRCP-PCTALL-GE010HI  DLY-PRCP-PCTALL-GE050HI  \
0                      NaN                      NaN                      NaN   
1                      NaN                      NaN                      NaN   
2                      NaN                      NaN                      NaN   
3                      NaN                      NaN                      NaN   
4                      NaN                      NaN                      NaN   

   DLY-PRCP-PCTALL-GE100HI  DLY-SNWD-PCTALL-GE001WI  DLY-SNWD-PCTALL-GE010WI  \
0                      NaN                      NaN                      NaN   
1                      NaN                      NaN                      NaN   
2                      NaN                      NaN                      NaN   
3                      NaN                      NaN                      NaN   
4                      NaN                      NaN                      NaN   

   DLY-SNWD-PCTALL-GE003WI  DLY-SNWD-PCTALL-GE005WI  DLY-SNOW-PCTALL-GE001TI  \
0                      NaN                      NaN                      NaN   
1                      NaN                      NaN                      NaN   
2                      NaN                      NaN                      NaN   
3                      NaN                      NaN                      NaN   
4                      NaN                      NaN                      NaN   

   DLY-SNOW-PCTALL-GE010TI  DLY-SNOW-PCTALL-GE100TI  DLY-SNOW-PCTALL-GE030TI  \
0                      NaN                      NaN                      NaN   
1                      NaN                      NaN                      NaN   
2                      NaN                      NaN                      NaN   
3                      NaN                      NaN                      NaN   
4                      NaN                      NaN                      NaN   

   DLY-SNOW-PCTALL-GE050TI          STATION_NAME_y ELEVATION  LATITUDE  \
0                      NaN  TWENTYNINE PALMS CA US       602  34.12806   
1                      NaN  TWENTYNINE PALMS CA US       602  34.12806   
2                      NaN  TWENTYNINE PALMS CA US       602  34.12806   
3                      NaN  TWENTYNINE PALMS CA US       602  34.12806   
4    

In [41]:
right_merged.shape

(127020, 48)

Здесь вы просто перевернули позиции входных фреймов данных и указали правильное соединение. Когда вы исследуете `right_merged`, вы можете заметить, что это не совсем то же самое, что `left_merged`. Единственная разница между ними заключается в порядке столбцов: столбцы первого ввода всегда будут первыми во вновь сформированном кадре данных.

## .присоединиться()
`.join()` внутри использует `merge()`, но предоставляет гораздо более упрощенный интерфейс для `merge()` и по умолчанию объединяется с индексами. Вот вводный пример использования параметров lsuffix и rsuffix для обработки перекрывающихся имен столбцов.

In [42]:
precip_one_station.join(climate_temp, lsuffix="_left", rsuffix="_right")

STATION_left       STATION_NAME_left  DATE_left  DLY-PRCP-25PCTL  \
1460  GHCND:USC00045721  MITCHELL CAVERNS CA US   20100101             0.04   
1461  GHCND:USC00045721  MITCHELL CAVERNS CA US   20100102             0.05   
1462  GHCND:USC00045721  MITCHELL CAVERNS CA US   20100103             0.05   
1463  GHCND:USC00045721  MITCHELL CAVERNS CA US   20100104             0.05   
1464  GHCND:USC00045721  MITCHELL CAVERNS CA US   20100105             0.05   
...                 ...                     ...        ...              ...   
1820  GHCND:USC00045721  MITCHELL CAVERNS CA US   20101227             0.04   
1821  GHCND:USC00045721  MITCHELL CAVERNS CA US   20101228             0.04   
1822  GHCND:USC00045721  MITCHELL CAVERNS CA US   20101229             0.04   
1823  GHCND:USC00045721  MITCHELL CAVERNS CA US   20101230             0.04   
1824  GHCND:USC00045721  MITCHELL CAVERNS CA US   20101231             0.04   

      DLY-SNWD-25PCTL  DLY-SNOW-25PCTL  DLY-PRCP-50PCTL  DLY-SNWD-50PCTL  \
1460             -666            -66.6             0.16             -666   
1461             -666            -66.6             0.16             -666   
1462             -666            -66.6             0.16             -666   
1463             -666            -66.6             0.16             -666   
1464             -666            -66.6             0.17             -666   
...               ...              ...              ...              ...   
1820             -666            -66.6             0.15             -666   
1821             -666            -66.6             0.15             -666   
1822             -666            -66.6             0.15             -666   
1823             -666            -66.6             0.15             -666   
1824             -666            -66.6             0.15             -666   

      DLY-SNOW-50PCTL  DLY-PRCP-75PCTL  DLY-SNWD-75PCTL  DLY-SNOW-75PCTL  \
1460            -66.6             0.44             -666            -66.6   
1461            -66.6             0.44             -666            -66.6   
1462            -66.6             0.45             -666            -66.6   
1463            -66.6             0.45             -666            -66.6   
1464            -66.6             0.46             -666            -66.6   
...               ...              ...              ...              ...   
1820            -66.6             0.44             -666            -66.6   
1821            -66.6             0.43             -666            -66.6   
1822            -66.6             0.43             -666            -66.6   
1823            -66.6             0.43             -666            -66.6   
1824            -66.6             0.44             -666            -66.6   

      MTD-PRCP-NORMAL  MTD-SNOW-NORMAL  YTD-PRCP-NORMAL  YTD-SNOW-NORMAL  \
1460             0.04              0.0             0.04              0.0   
1461             0.08              0.0             0.08              0.0   
1462             0.12              0.0             0.12              0.0   
1463             0.16              0.0             0.16              0.0   
1464             0.21              0.0             0.21              0.0   
...               ...              ...              ...              ...   
1820             1.14              0.3            11.29              1.5   
1821             1.19              0.3            11.34              1.5   
1822             1.24              0.3            11.39              1.5   
1823             1.30              0.3            11.45              1.5   
1824             1.35              0.3            11.50              1.5   

      DLY-PRCP-PCTALL-GE001HI  DLY-PRCP-PCTALL-GE010HI  \
1460                      137                       81   
1461                      138                       83   
1462                      139                       84   
1463                      140                       85   
1464                      141    

Если вы проверите данные, вы увидите, что перекрывающиеся столбцы сохранены, просто переименованы, чтобы быть уникальными. Если мы перевернем это и вместо этого вызовем `.join()` для большего DataFrame, вы заметите, что DataFrame больше, но данные, которые не существуют в меньшем DataFrame (`precip_one_station`), заполняются ` NaN` (_не число_).

In [43]:
climate_temp.join(precip_one_station, lsuffix="_left", rsuffix="_right")

STATION_left       STATION_NAME_left ELEVATION  LATITUDE  \
0       GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806   
1       GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806   
2       GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806   
3       GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806   
4       GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806   
...                   ...                     ...       ...       ...   
127015  GHCND:USC00046006  MOUNT WILSON CBS CA US    1740.4   34.2308   
127016  GHCND:USC00046006  MOUNT WILSON CBS CA US    1740.4   34.2308   
127017  GHCND:USC00046006  MOUNT WILSON CBS CA US    1740.4   34.2308   
127018  GHCND:USC00046006  MOUNT WILSON CBS CA US    1740.4   34.2308   
127019  GHCND:USC00046006  MOUNT WILSON CBS CA US    1740.4   34.2308   

         LONGITUDE  DATE_left  DLY-CLDD-BASE45  DLY-CLDD-BASE50  \
0       -116.03694   20100101                6                2   
1       -116.03694   20100102                6                2   
2       -116.03694   20100103                6                2   
3       -116.03694   20100104                6                2   
4       -116.03694   20100105                6                2   
...            ...        ...              ...              ...   
127015   -118.0711   20101227                4                2   
127016   -118.0711   20101228                4                2   
127017   -118.0711   20101229                4                2   
127018   -118.0711   20101230                4                2   
127019   -118.0711   20101231                4                2   

        DLY-CLDD-BASE55  DLY-CLDD-BASE57  DLY-CLDD-BASE60  DLY-CLDD-NORMAL  \
0                 -7777            -7777            -7777                0   
1                     1            -7777            -7777                0   
2                     1            -7777            -7777                0   
3                     1            -7777            -7777                0   
4                     1            -7777            -7777                0   
...                 ...              ...              ...              ...   
127015                1            -7777            -7777            -7777   
127016                1            -7777            -7777            -7777   
127017                1            -7777            -7777            -7777   
127018                1            -7777            -7777            -7777   
127019                1            -7777            -7777            -7777   

        DLY-CLDD-BASE70  DLY-CLDD-BASE72  DLY-HTDD-BASE40  DLY-HTDD-BASE45  \
0                     0                0            -7777                1   
1                     0                0            -7777                1   
2                     0                0            -7777                1   
3                     0                0            -7777                1   
4                     0                0            -7777            -7777   
...                 ...              ...              ...              ...   
127015                0                0                2                4   
127016                0                0                2                3   
127017                0                0                2                3   
127018                0                0                2                3   
127019                0                0                1                3   

        DLY-HTDD-BASE50  DLY-HTDD-BASE55  DLY-HTDD-BASE57  DLY-HTDD-BASE60  \
0                     2                6                7               10   
1                     2                6                7               10   
2                     2                5                7               10   
3                     2                5                7               10   
4                     2                5                7          

If you must use `.join()` and want to merge the columns, you must set them to be indexes first. First take a look at this previously used `merge()` operation:

In [44]:
inner_merged_total = pd.merge(
    climate_temp, climate_precip, on=["STATION", "DATE"]
)
inner_merged_total.head()

STATION          STATION_NAME_x ELEVATION  LATITUDE   LONGITUDE  \
0  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
1  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
2  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
3  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
4  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   

       DATE  DLY-CLDD-BASE45  DLY-CLDD-BASE50  DLY-CLDD-BASE55  \
0  20100101                6                2            -7777   
1  20100102                6                2                1   
2  20100103                6                2                1   
3  20100104                6                2                1   
4  20100105                6                2                1   

   DLY-CLDD-BASE57  DLY-CLDD-BASE60  DLY-CLDD-NORMAL  DLY-CLDD-BASE70  \
0            -7777            -7777                0                0   
1            -7777            -7777                0                0   
2            -7777            -7777                0                0   
3            -7777            -7777                0                0   
4            -7777            -7777                0                0   

   DLY-CLDD-BASE72  DLY-HTDD-BASE40  DLY-HTDD-BASE45  DLY-HTDD-BASE50  \
0                0            -7777                1                2   
1                0            -7777                1                2   
2                0            -7777                1                2   
3                0            -7777                1                2   
4                0            -7777            -7777                2   

   DLY-HTDD-BASE55  DLY-HTDD-BASE57  DLY-HTDD-BASE60  DLY-HTDD-NORMAL  \
0                6                7               10               15   
1                6                7               10               15   
2                5                7               10               15   
3                5                7               10               15   
4                5                7               10               15   

           STATION_NAME_y  DLY-PRCP-25PCTL  DLY-SNWD-25PCTL  DLY-SNOW-25PCTL  \
0  TWENTYNINE PALMS CA US            -6.66             -666            -66.6   
1  TWENTYNINE PALMS CA US            -6.66             -666            -66.6   
2  TWENTYNINE PALMS CA US            -6.66             -666            -66.6   
3  TWENTYNINE PALMS CA US            -6.66            -9999          -9999.0   
4  TWENTYNINE PALMS CA US            -6.66            -9999          -9999.0   

   DLY-PRCP-50PCTL  DLY-SNWD-50PCTL  DLY-SNOW-50PCTL  DLY-PRCP-75PCTL  \
0            -6.66             -666            -66.6            -6.66   
1            -6.66             -666            -66.6            -6.66   
2            -6.66             -666            -66.6            -6.66   
3            -6.66            -9999          -9999.0            -6.66   
4            -6.66            -9999          -9999.0            -6.66   

   DLY-SNWD-75PCTL  DLY-SNOW-75PCTL  MTD-PRCP-NORMAL  MTD-SNOW-NORMAL  \
0             -666            -66.6             0.02              0.0   
1             -666            -66.6             0.04              0.0   
2             -666            -66.6             0.05              0.0   
3            -9999          -9999.0             0.07              0.0   
4            -9999          -9999.0             0.09              0.0   

   YTD-PRCP-NORMAL  YTD-SNOW-NORMAL  DLY-PRCP-PCTALL-GE001HI  \
0             0.02              0.0                       98   
1             0.04              0.0                       99   
2             0.05              0.0                      100   
3             0.07              0.0                      101   
4             0.09              0.0                      102   

   DLY-PRCP-PCTALL-GE010HI  DLY-PRCP-PCTALL-GE050HI  DLY-PRCP-PCTALL-GE100

In [45]:
inner_joined_total = climate_temp.join(
    climate_precip.set_index(["STATION", "DATE"]),
    on=["STATION", "DATE"],
    how="inner",
    lsuffix="_x",
    rsuffix="_y",
)
inner_joined_total.head()

STATION          STATION_NAME_x ELEVATION  LATITUDE   LONGITUDE  \
0  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
1  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
2  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
3  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
4  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   

       DATE  DLY-CLDD-BASE45  DLY-CLDD-BASE50  DLY-CLDD-BASE55  \
0  20100101                6                2            -7777   
1  20100102                6                2                1   
2  20100103                6                2                1   
3  20100104                6                2                1   
4  20100105                6                2                1   

   DLY-CLDD-BASE57  DLY-CLDD-BASE60  DLY-CLDD-NORMAL  DLY-CLDD-BASE70  \
0            -7777            -7777                0                0   
1            -7777            -7777                0                0   
2            -7777            -7777                0                0   
3            -7777            -7777                0                0   
4            -7777            -7777                0                0   

   DLY-CLDD-BASE72  DLY-HTDD-BASE40  DLY-HTDD-BASE45  DLY-HTDD-BASE50  \
0                0            -7777                1                2   
1                0            -7777                1                2   
2                0            -7777                1                2   
3                0            -7777                1                2   
4                0            -7777            -7777                2   

   DLY-HTDD-BASE55  DLY-HTDD-BASE57  DLY-HTDD-BASE60  DLY-HTDD-NORMAL  \
0                6                7               10               15   
1                6                7               10               15   
2                5                7               10               15   
3                5                7               10               15   
4                5                7               10               15   

           STATION_NAME_y  DLY-PRCP-25PCTL  DLY-SNWD-25PCTL  DLY-SNOW-25PCTL  \
0  TWENTYNINE PALMS CA US            -6.66             -666            -66.6   
1  TWENTYNINE PALMS CA US            -6.66             -666            -66.6   
2  TWENTYNINE PALMS CA US            -6.66             -666            -66.6   
3  TWENTYNINE PALMS CA US            -6.66            -9999          -9999.0   
4  TWENTYNINE PALMS CA US            -6.66            -9999          -9999.0   

   DLY-PRCP-50PCTL  DLY-SNWD-50PCTL  DLY-SNOW-50PCTL  DLY-PRCP-75PCTL  \
0            -6.66             -666            -66.6            -6.66   
1            -6.66             -666            -66.6            -6.66   
2            -6.66             -666            -66.6            -6.66   
3            -6.66            -9999          -9999.0            -6.66   
4            -6.66            -9999          -9999.0            -6.66   

   DLY-SNWD-75PCTL  DLY-SNOW-75PCTL  MTD-PRCP-NORMAL  MTD-SNOW-NORMAL  \
0             -666            -66.6             0.02              0.0   
1             -666            -66.6             0.04              0.0   
2             -666            -66.6             0.05              0.0   
3            -9999          -9999.0             0.07              0.0   
4            -9999          -9999.0             0.09              0.0   

   YTD-PRCP-NORMAL  YTD-SNOW-NORMAL  DLY-PRCP-PCTALL-GE001HI  \
0             0.02              0.0                       98   
1             0.04              0.0                       99   
2             0.05              0.0                      100   
3             0.07              0.0                      101   
4             0.09              0.0                      102   

   DLY-PRCP-PCTALL-GE010HI  DLY-PRCP-PCTALL-GE050HI  DLY-PRCP-PCTALL-GE100

Because `.join()` works on indexes, if we want to recreate `merge()` before, then we must set indexes on the join columns we specify. In this example, you used the `.set_index()` method to set your indexes to the key columns within the join. 

Below you will see an almost-bare `.join()` call. Because there are overlapping columns, you will have to specify a suffix with `lsuffix`, `rsuffix`, or both, but this example will demonstrate the more typical behavior of `.join()`.

In [46]:
climate_temp.join(climate_precip, lsuffix="_left")

STATION_left       STATION_NAME_left ELEVATION  LATITUDE  \
0       GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806   
1       GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806   
2       GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806   
3       GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806   
4       GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806   
...                   ...                     ...       ...       ...   
127015  GHCND:USC00046006  MOUNT WILSON CBS CA US    1740.4   34.2308   
127016  GHCND:USC00046006  MOUNT WILSON CBS CA US    1740.4   34.2308   
127017  GHCND:USC00046006  MOUNT WILSON CBS CA US    1740.4   34.2308   
127018  GHCND:USC00046006  MOUNT WILSON CBS CA US    1740.4   34.2308   
127019  GHCND:USC00046006  MOUNT WILSON CBS CA US    1740.4   34.2308   

         LONGITUDE  DATE_left  DLY-CLDD-BASE45  DLY-CLDD-BASE50  \
0       -116.03694   20100101                6                2   
1       -116.03694   20100102                6                2   
2       -116.03694   20100103                6                2   
3       -116.03694   20100104                6                2   
4       -116.03694   20100105                6                2   
...            ...        ...              ...              ...   
127015   -118.0711   20101227                4                2   
127016   -118.0711   20101228                4                2   
127017   -118.0711   20101229                4                2   
127018   -118.0711   20101230                4                2   
127019   -118.0711   20101231                4                2   

        DLY-CLDD-BASE55  DLY-CLDD-BASE57  DLY-CLDD-BASE60  DLY-CLDD-NORMAL  \
0                 -7777            -7777            -7777                0   
1                     1            -7777            -7777                0   
2                     1            -7777            -7777                0   
3                     1            -7777            -7777                0   
4                     1            -7777            -7777                0   
...                 ...              ...              ...              ...   
127015                1            -7777            -7777            -7777   
127016                1            -7777            -7777            -7777   
127017                1            -7777            -7777            -7777   
127018                1            -7777            -7777            -7777   
127019                1            -7777            -7777            -7777   

        DLY-CLDD-BASE70  DLY-CLDD-BASE72  DLY-HTDD-BASE40  DLY-HTDD-BASE45  \
0                     0                0            -7777                1   
1                     0                0            -7777                1   
2                     0                0            -7777                1   
3                     0                0            -7777                1   
4                     0                0            -7777            -7777   
...                 ...              ...              ...              ...   
127015                0                0                2                4   
127016                0                0                2                3   
127017                0                0                2                3   
127018                0                0                2                3   
127019                0                0                1                3   

        DLY-HTDD-BASE50  DLY-HTDD-BASE55  DLY-HTDD-BASE57  DLY-HTDD-BASE60  \
0                     2                6                7               10   
1                     2                6                7               10   
2                     2                5                7               10   
3                     2                5                7               10   
4                     2                5                7          

## concat()


Во-первых, вы выполните базовую конкатенацию вдоль оси по умолчанию, используя кадры данных, с которыми вы играли в этом руководстве:

In [47]:
double_precip = pd.concat([precip_one_station, precip_one_station])
double_precip.head()

STATION            STATION_NAME      DATE  DLY-PRCP-25PCTL  \
1460  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100101             0.04   
1461  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100102             0.05   
1462  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100103             0.05   
1463  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100104             0.05   
1464  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100105             0.05   

      DLY-SNWD-25PCTL  DLY-SNOW-25PCTL  DLY-PRCP-50PCTL  DLY-SNWD-50PCTL  \
1460             -666            -66.6             0.16             -666   
1461             -666            -66.6             0.16             -666   
1462             -666            -66.6             0.16             -666   
1463             -666            -66.6             0.16             -666   
1464             -666            -66.6             0.17             -666   

      DLY-SNOW-50PCTL  DLY-PRCP-75PCTL  DLY-SNWD-75PCTL  DLY-SNOW-75PCTL  \
1460            -66.6             0.44             -666            -66.6   
1461            -66.6             0.44             -666            -66.6   
1462            -66.6             0.45             -666            -66.6   
1463            -66.6             0.45             -666            -66.6   
1464            -66.6             0.46             -666            -66.6   

      MTD-PRCP-NORMAL  MTD-SNOW-NORMAL  YTD-PRCP-NORMAL  YTD-SNOW-NORMAL  \
1460             0.04              0.0             0.04              0.0   
1461             0.08              0.0             0.08              0.0   
1462             0.12              0.0             0.12              0.0   
1463             0.16              0.0             0.16              0.0   
1464             0.21              0.0             0.21              0.0   

      DLY-PRCP-PCTALL-GE001HI  DLY-PRCP-PCTALL-GE010HI  \
1460                      137                       81   
1461                      138                       83   
1462                      139                       84   
1463                      140                       85   
1464                      141                       86   

      DLY-PRCP-PCTALL-GE050HI  DLY-PRCP-PCTALL-GE100HI  \
1460                       31                       11   
1461                       31                       11   
1462                       31                       11   
1463                       32                       11   
1464                       32                       11   

      DLY-SNWD-PCTALL-GE001WI  DLY-SNWD-PCTALL-GE010WI  \
1460                        4                        0   
1461                        4                        0   
1462                        4                        0   
1463                        4                        0   
1464                        4                        0   

      DLY-SNWD-PCTALL-GE003WI  DLY-SNWD-PCTALL-GE005WI  \
1460                        3                        3   
1461                        3                        3   
1462                        3                        3   
1463                        3                        2   
1464                        3                        2   

      DLY-SNOW-PCTALL-GE001TI  DLY-SNOW-PCTALL-GE010TI  \
1460                        9                        6   
1461                       10                        6   
1462                       10                        6   
1463                       10                        6   
1464                       10                        6   

      DLY-SNOW-PCTALL-GE100TI  DLY-SNOW-PCTALL-GE030TI  \
1460                        0                    -9999   
1461                        0                    -9999   
1462                        0                    -9999   
1463                        0                    -9999   
1464                        0                    -9999   

      DLY-SNOW-PCTALL-GE050TI  
1460                    -9999  
1461              

In [48]:
double_precip.shape

(730, 29)

In [50]:
precip_one_station.shape

(365, 29)

Этот очень прост по дизайну. Здесь вы создали DataFrame, который является дубликатом небольшого DataFrame, созданного ранее. Следует заметить, что индексы повторяются. Если вам нужен новый индекс, основанный на 0, вы можете использовать ignore_index параметр:



In [51]:
reindexed = pd.concat(
    [precip_one_station, precip_one_station], ignore_index=True
)
reindexed.head()

STATION            STATION_NAME      DATE  DLY-PRCP-25PCTL  \
0  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100101             0.04   
1  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100102             0.05   
2  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100103             0.05   
3  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100104             0.05   
4  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100105             0.05   

   DLY-SNWD-25PCTL  DLY-SNOW-25PCTL  DLY-PRCP-50PCTL  DLY-SNWD-50PCTL  \
0             -666            -66.6             0.16             -666   
1             -666            -66.6             0.16             -666   
2             -666            -66.6             0.16             -666   
3             -666            -66.6             0.16             -666   
4             -666            -66.6             0.17             -666   

   DLY-SNOW-50PCTL  DLY-PRCP-75PCTL  DLY-SNWD-75PCTL  DLY-SNOW-75PCTL  \
0            -66.6             0.44             -666            -66.6   
1            -66.6             0.44             -666            -66.6   
2            -66.6             0.45             -666            -66.6   
3            -66.6             0.45             -666            -66.6   
4            -66.6             0.46             -666            -66.6   

   MTD-PRCP-NORMAL  MTD-SNOW-NORMAL  YTD-PRCP-NORMAL  YTD-SNOW-NORMAL  \
0             0.04              0.0             0.04              0.0   
1             0.08              0.0             0.08              0.0   
2             0.12              0.0             0.12              0.0   
3             0.16              0.0             0.16              0.0   
4             0.21              0.0             0.21              0.0   

   DLY-PRCP-PCTALL-GE001HI  DLY-PRCP-PCTALL-GE010HI  DLY-PRCP-PCTALL-GE050HI  \
0                      137                       81                       31   
1                      138                       83                       31   
2                      139                       84                       31   
3                      140                       85                       32   
4                      141                       86                       32   

   DLY-PRCP-PCTALL-GE100HI  DLY-SNWD-PCTALL-GE001WI  DLY-SNWD-PCTALL-GE010WI  \
0                       11                        4                        0   
1                       11                        4                        0   
2                       11                        4                        0   
3                       11                        4                        0   
4                       11                        4                        0   

   DLY-SNWD-PCTALL-GE003WI  DLY-SNWD-PCTALL-GE005WI  DLY-SNOW-PCTALL-GE001TI  \
0                        3                        3                        9   
1                        3                        3                       10   
2                        3                        3                       10   
3                        3                        2                       10   
4                        3                        2                       10   

   DLY-SNOW-PCTALL-GE010TI  DLY-SNOW-PCTALL-GE100TI  DLY-SNOW-PCTALL-GE030TI  \
0                        6                        0                    -9999   
1                        6                        0                    -9999   
2                        6                        0                    -9999   
3                        6                        0                    -9999   
4                        6                        0                    -9999   

   DLY-SNOW-PCTALL-GE050TI  
0                    -9999  
1                    -9999  
2                    -9999  
3                    -9999  
4                    -9999

In [52]:
reindexed.shape

(730, 29)

When axis labels for the axis you are **not** concatenating along don't match (for example, column labels when concatenating along rows), then all columns are preserved and missing data is filled in with `NaN`. 

In [53]:
outer_joined = pd.concat([climate_precip, climate_temp])
outer_joined.head()

STATION            STATION_NAME      DATE  DLY-PRCP-25PCTL  \
0  GHCND:USC00049099  TWENTYNINE PALMS CA US  20100101            -6.66   
1  GHCND:USC00049099  TWENTYNINE PALMS CA US  20100102            -6.66   
2  GHCND:USC00049099  TWENTYNINE PALMS CA US  20100103            -6.66   
3  GHCND:USC00049099  TWENTYNINE PALMS CA US  20100104            -6.66   
4  GHCND:USC00049099  TWENTYNINE PALMS CA US  20100105            -6.66   

   DLY-SNWD-25PCTL  DLY-SNOW-25PCTL  DLY-PRCP-50PCTL  DLY-SNWD-50PCTL  \
0           -666.0            -66.6            -6.66           -666.0   
1           -666.0            -66.6            -6.66           -666.0   
2           -666.0            -66.6            -6.66           -666.0   
3          -9999.0          -9999.0            -6.66          -9999.0   
4          -9999.0          -9999.0            -6.66          -9999.0   

   DLY-SNOW-50PCTL  DLY-PRCP-75PCTL  DLY-SNWD-75PCTL  DLY-SNOW-75PCTL  \
0            -66.6            -6.66           -666.0            -66.6   
1            -66.6            -6.66           -666.0            -66.6   
2            -66.6            -6.66           -666.0            -66.6   
3          -9999.0            -6.66          -9999.0          -9999.0   
4          -9999.0            -6.66          -9999.0          -9999.0   

   MTD-PRCP-NORMAL  MTD-SNOW-NORMAL  YTD-PRCP-NORMAL  YTD-SNOW-NORMAL  \
0             0.02              0.0             0.02              0.0   
1             0.04              0.0             0.04              0.0   
2             0.05              0.0             0.05              0.0   
3             0.07              0.0             0.07              0.0   
4             0.09              0.0             0.09              0.0   

   DLY-PRCP-PCTALL-GE001HI  DLY-PRCP-PCTALL-GE010HI  DLY-PRCP-PCTALL-GE050HI  \
0                     98.0                     43.0                     12.0   
1                     99.0                     44.0                     12.0   
2                    100.0                     44.0                     12.0   
3                    101.0                     45.0                     12.0   
4                    102.0                     45.0                     12.0   

   DLY-PRCP-PCTALL-GE100HI  DLY-SNWD-PCTALL-GE001WI  DLY-SNWD-PCTALL-GE010WI  \
0                      3.0                  -9999.0                      0.0   
1                      3.0                  -9999.0                      0.0   
2                      3.0                  -9999.0                      0.0   
3                      3.0                      0.0                      0.0   
4                      3.0                      0.0                      0.0   

   DLY-SNWD-PCTALL-GE003WI  DLY-SNWD-PCTALL-GE005WI  DLY-SNOW-PCTALL-GE001TI  \
0                  -9999.0                  -9999.0                  -9999.0   
1                  -9999.0                  -9999.0                  -9999.0   
2                  -9999.0                  -9999.0                  -9999.0   
3                      0.0                      0.0                      0.0   
4                      0.0                      0.0                      0.0   

   DLY-SNOW-PCTALL-GE010TI  DLY-SNOW-PCTALL-GE100TI  DLY-SNOW-PCTALL-GE030TI  \
0                  -9999.0                      0.0                  -9999.0   
1                  -9999.0                      0.0                  -9999.0   
2                  -9999.0                      0.0                  -9999.0   
3                      0.0                      0.0                      0.0   
4                      0.0                      0.0                      0.0   

   DLY-SNOW-PCTALL-GE050TI ELEVATION LATITUDE LONGITUDE  DLY-CLDD-BASE45  \
0                  -9999.0       NaN      NaN       NaN              NaN   
1                  -9999.0       NaN      NaN       NaN              NaN   
2                  -9999.0       NaN      NaN       NaN              NaN   
3                

Как отмечалось ранее, если вы объединяете по оси 0 (строки), но имеете несовпадающие метки на оси 1 (столбцы), то эти столбцы будут добавлены и заполнены NaN значениями. Это приводит к внешнему соединению

In [54]:
outer_joined.shape

(278130, 47)

In [48]:
outer_joined

STATION            STATION_NAME      DATE  DLY-PRCP-25PCTL  \
0       GHCND:USC00049099  TWENTYNINE PALMS CA US  20100101            -6.66   
1       GHCND:USC00049099  TWENTYNINE PALMS CA US  20100102            -6.66   
2       GHCND:USC00049099  TWENTYNINE PALMS CA US  20100103            -6.66   
3       GHCND:USC00049099  TWENTYNINE PALMS CA US  20100104            -6.66   
4       GHCND:USC00049099  TWENTYNINE PALMS CA US  20100105            -6.66   
...                   ...                     ...       ...              ...   
127015  GHCND:USC00046006  MOUNT WILSON CBS CA US  20101227              NaN   
127016  GHCND:USC00046006  MOUNT WILSON CBS CA US  20101228              NaN   
127017  GHCND:USC00046006  MOUNT WILSON CBS CA US  20101229              NaN   
127018  GHCND:USC00046006  MOUNT WILSON CBS CA US  20101230              NaN   
127019  GHCND:USC00046006  MOUNT WILSON CBS CA US  20101231              NaN   

        DLY-SNWD-25PCTL  DLY-SNOW-25PCTL  DLY-PRCP-50PCTL  DLY-SNWD-50PCTL  \
0                -666.0            -66.6            -6.66           -666.0   
1                -666.0            -66.6            -6.66           -666.0   
2                -666.0            -66.6            -6.66           -666.0   
3               -9999.0          -9999.0            -6.66          -9999.0   
4               -9999.0          -9999.0            -6.66          -9999.0   
...                 ...              ...              ...              ...   
127015              NaN              NaN              NaN              NaN   
127016              NaN              NaN              NaN              NaN   
127017              NaN              NaN              NaN              NaN   
127018              NaN              NaN              NaN              NaN   
127019              NaN              NaN              NaN              NaN   

        DLY-SNOW-50PCTL  DLY-PRCP-75PCTL  DLY-SNWD-75PCTL  DLY-SNOW-75PCTL  \
0                 -66.6            -6.66           -666.0            -66.6   
1                 -66.6            -6.66           -666.0            -66.6   
2                 -66.6            -6.66           -666.0            -66.6   
3               -9999.0            -6.66          -9999.0          -9999.0   
4               -9999.0            -6.66          -9999.0          -9999.0   
...                 ...              ...              ...              ...   
127015              NaN              NaN              NaN              NaN   
127016              NaN              NaN              NaN              NaN   
127017              NaN              NaN              NaN              NaN   
127018              NaN              NaN              NaN              NaN   
127019              NaN              NaN              NaN              NaN   

        MTD-PRCP-NORMAL  MTD-SNOW-NORMAL  YTD-PRCP-NORMAL  YTD-SNOW-NORMAL  \
0                  0.02              0.0             0.02              0.0   
1                  0.04              0.0             0.04              0.0   
2                  0.05              0.0             0.05              0.0   
3                  0.07              0.0             0.07              0.0   
4                  0.09              0.0             0.09              0.0   
...                 ...              ...              ...              ...   
127015              NaN              NaN              NaN              NaN   
127016              NaN              NaN              NaN              NaN   
127017              NaN              NaN              NaN              NaN   
127018              NaN              NaN              NaN              NaN   
127019              NaN              NaN              NaN              NaN   

        DLY-PRCP-PCTALL-GE001HI  DLY-PRCP-PCTALL-GE010HI  \
0                          98.0                     43.0   
1                          99.0                     44.0   
2                         100.0                     44.0   
3     

С этими двумя кадрами данных, поскольку вы просто объединяете строки, очень немногие столбцы имеют одинаковое имя. Это означает, что вы увидите множество столбцов со NaNзначениями.

Чтобы вместо этого удалить столбцы с отсутствующими данными, используйте joinпараметр со значением "inner"для выполнения внутреннего соединения:

In [55]:
inner_joined = pd.concat([climate_temp, climate_precip], join="inner")
inner_joined.head()

STATION            STATION_NAME      DATE
0  GHCND:USC00049099  TWENTYNINE PALMS CA US  20100101
1  GHCND:USC00049099  TWENTYNINE PALMS CA US  20100102
2  GHCND:USC00049099  TWENTYNINE PALMS CA US  20100103
3  GHCND:USC00049099  TWENTYNINE PALMS CA US  20100104
4  GHCND:USC00049099  TWENTYNINE PALMS CA US  20100105

In [56]:
inner_joined.shape

(278130, 3)

Используя внутреннее соединение, у вас останутся только те столбцы, которые являются общими для исходных фреймов данных: STATION, STATION_NAME, и DATE.

Вы также можете перевернуть это, установив axis параметр:

In [57]:
inner_joined_cols = pd.concat(
    [climate_temp, climate_precip], axis="columns", join="inner"
)
inner_joined.head()

STATION            STATION_NAME      DATE
0  GHCND:USC00049099  TWENTYNINE PALMS CA US  20100101
1  GHCND:USC00049099  TWENTYNINE PALMS CA US  20100102
2  GHCND:USC00049099  TWENTYNINE PALMS CA US  20100103
3  GHCND:USC00049099  TWENTYNINE PALMS CA US  20100104
4  GHCND:USC00049099  TWENTYNINE PALMS CA US  20100105

In [58]:
inner_joined_cols.shape

(127020, 50)

Теперь у вас есть только строки, содержащие данные для всех столбцов в обоих кадрах данных. Не случайно количество строк соответствует количеству меньшего DataFrame.

Еще один полезный прием для конкатенации — использование keys параметра для создания меток иерархической оси. Это полезно, если вы хотите сохранить индексы или имена столбцов исходных наборов данных, но также хотите добавить новые:

In [59]:
hierarchical_keys = pd.concat(
    [climate_temp, climate_precip], keys=["temp", "precip"]
)
hierarchical_keys.head()

STATION            STATION_NAME ELEVATION  LATITUDE  \
temp 0  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806   
     1  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806   
     2  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806   
     3  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806   
     4  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806   

         LONGITUDE      DATE  DLY-CLDD-BASE45  DLY-CLDD-BASE50  \
temp 0  -116.03694  20100101              6.0              2.0   
     1  -116.03694  20100102              6.0              2.0   
     2  -116.03694  20100103              6.0              2.0   
     3  -116.03694  20100104              6.0              2.0   
     4  -116.03694  20100105              6.0              2.0   

        DLY-CLDD-BASE55  DLY-CLDD-BASE57  DLY-CLDD-BASE60  DLY-CLDD-NORMAL  \
temp 0          -7777.0          -7777.0          -7777.0              0.0   
     1              1.0          -7777.0          -7777.0              0.0   
     2              1.0          -7777.0          -7777.0              0.0   
     3              1.0          -7777.0          -7777.0              0.0   
     4              1.0          -7777.0          -7777.0              0.0   

        DLY-CLDD-BASE70  DLY-CLDD-BASE72  DLY-HTDD-BASE40  DLY-HTDD-BASE45  \
temp 0              0.0              0.0          -7777.0              1.0   
     1              0.0              0.0          -7777.0              1.0   
     2              0.0              0.0          -7777.0              1.0   
     3              0.0              0.0          -7777.0              1.0   
     4              0.0              0.0          -7777.0          -7777.0   

        DLY-HTDD-BASE50  DLY-HTDD-BASE55  DLY-HTDD-BASE57  DLY-HTDD-BASE60  \
temp 0              2.0              6.0              7.0             10.0   
     1              2.0              6.0              7.0             10.0   
     2              2.0              5.0              7.0             10.0   
     3              2.0              5.0              7.0             10.0   
     4              2.0              5.0              7.0             10.0   

        DLY-HTDD-NORMAL  DLY-PRCP-25PCTL  DLY-SNWD-25PCTL  DLY-SNOW-25PCTL  \
temp 0             15.0              NaN              NaN              NaN   
     1             15.0              NaN              NaN              NaN   
     2             15.0              NaN              NaN              NaN   
     3             15.0              NaN              NaN              NaN   
     4             15.0              NaN              NaN              NaN   

        DLY-PRCP-50PCTL  DLY-SNWD-50PCTL  DLY-SNOW-50PCTL  DLY-PRCP-75PCTL  \
temp 0              NaN              NaN              NaN              NaN   
     1              NaN              NaN              NaN              NaN   
     2              NaN              NaN              NaN              NaN   
     3              NaN              NaN              NaN              NaN   
     4              NaN              NaN              NaN              NaN   

        DLY-SNWD-75PCTL  DLY-SNOW-75PCTL  MTD-PRCP-NORMAL  MTD-SNOW-NORMAL  \
temp 0              NaN              NaN              NaN              NaN   
     1              NaN              NaN              NaN              NaN   
     2              NaN              NaN              NaN              NaN   
     3              NaN              NaN              NaN              NaN   
     4              NaN              NaN              NaN              NaN   

        YTD-PRCP-NORMAL  YTD-SNOW-NORMAL  DLY-PRCP-PCTALL-GE001HI  \
temp 0              NaN              NaN                      NaN   
     1              NaN              NaN                      NaN   
     2              NaN              NaN                      NaN   
     3              NaN              NaN                      NaN   
     4              NaN

In [62]:
hierarchical_keys.tail()

STATION            STATION_NAME ELEVATION LATITUDE  \
precip 151105  GHCND:USC00046006  MOUNT WILSON CBS CA US       NaN      NaN   
       151106  GHCND:USC00046006  MOUNT WILSON CBS CA US       NaN      NaN   
       151107  GHCND:USC00046006  MOUNT WILSON CBS CA US       NaN      NaN   
       151108  GHCND:USC00046006  MOUNT WILSON CBS CA US       NaN      NaN   
       151109  GHCND:USC00046006  MOUNT WILSON CBS CA US       NaN      NaN   

              LONGITUDE      DATE  DLY-CLDD-BASE45  DLY-CLDD-BASE50  \
precip 151105       NaN  20101227              NaN              NaN   
       151106       NaN  20101228              NaN              NaN   
       151107       NaN  20101229              NaN              NaN   
       151108       NaN  20101230              NaN              NaN   
       151109       NaN  20101231              NaN              NaN   

               DLY-CLDD-BASE55  DLY-CLDD-BASE57  DLY-CLDD-BASE60  \
precip 151105              NaN              NaN              NaN   
       151106              NaN              NaN              NaN   
       151107              NaN              NaN              NaN   
       151108              NaN              NaN              NaN   
       151109              NaN              NaN              NaN   

               DLY-CLDD-NORMAL  DLY-CLDD-BASE70  DLY-CLDD-BASE72  \
precip 151105              NaN              NaN              NaN   
       151106              NaN              NaN              NaN   
       151107              NaN              NaN              NaN   
       151108              NaN              NaN              NaN   
       151109              NaN              NaN              NaN   

               DLY-HTDD-BASE40  DLY-HTDD-BASE45  DLY-HTDD-BASE50  \
precip 151105              NaN              NaN              NaN   
       151106              NaN              NaN              NaN   
       151107              NaN              NaN              NaN   
       151108              NaN              NaN              NaN   
       151109              NaN              NaN              NaN   

               DLY-HTDD-BASE55  DLY-HTDD-BASE57  DLY-HTDD-BASE60  \
precip 151105              NaN              NaN              NaN   
       151106              NaN              NaN              NaN   
       151107              NaN              NaN              NaN   
       151108              NaN              NaN              NaN   
       151109              NaN              NaN              NaN   

               DLY-HTDD-NORMAL  DLY-PRCP-25PCTL  DLY-SNWD-25PCTL  \
precip 151105              NaN             0.12          -9999.0   
       151106              NaN             0.12          -9999.0   
       151107              NaN             0.12          -9999.0   
       151108              NaN             0.12          -9999.0   
       151109              NaN             0.12          -9999.0   

               DLY-SNOW-25PCTL  DLY-PRCP-50PCTL  DLY-SNWD-50PCTL  \
precip 151105          -9999.0             0.41          -9999.0   
       151106          -9999.0             0.42          -9999.0   
       151107          -9999.0             0.43          -9999.0   
       151108          -9999.0             0.43          -9999.0   
       151109          -9999.0             0.44          -9999.0   

               DLY-SNOW-50PCTL  DLY-PRCP-75PCTL  DLY-SNWD-75PCTL  \
precip 151105          -9999.0             1.13          -9999.0   
       151106          -9999.0             1.14          -9999.0   
       151107          -9999.0             1.15          -9999.0   
       151108          -9999.0             1.15          -9999.0   
       151109          -9999.0             1.16          -9999.0   

               DLY-SNOW-75PCTL  MTD-PRCP-NORMAL  MTD-SNOW-NORMAL  \
precip 151105          -9999.0             3.91          -9999.0   
       151106          -9999.0             4.10          -9999.0   
       151107          -9999.0             4.30         

In [61]:
hierarchical_keys.index

MultiIndex([(  'temp',      0),
            (  'temp',      1),
            (  'temp',      2),
            (  'temp',      3),
            (  'temp',      4),
            (  'temp',      5),
            (  'temp',      6),
            (  'temp',      7),
            (  'temp',      8),
            (  'temp',      9),
            ...
            ('precip', 151100),
            ('precip', 151101),
            ('precip', 151102),
            ('precip', 151103),
            ('precip', 151104),
            ('precip', 151105),
            ('precip', 151106),
            ('precip', 151107),
            ('precip', 151108),
            ('precip', 151109)],
           length=278130)